import tkinter as tk

root=tk.Tk()
root.geometry("690x690")
root.title("Gato Fractal!")

cat=[
    [
        tk.Frame(root,bg="purple",width=250,height=250,highlightbackground="white",highlightthickness=2),
        tk.Frame(root,bg="purple",width=250,height=250,highlightbackground="white",highlightthickness=2),
        tk.Frame(root,bg="purple",width=250,height=250,highlightbackground="white",highlightthickness=2)
    ],
    [
        tk.Frame(root,bg="purple",width=250,height=250,highlightbackground="white",highlightthickness=2),
        tk.Frame(root,bg="purple",width=250,height=250,highlightbackground="white",highlightthickness=2),
        tk.Frame(root,bg="purple",width=250,height=250,highlightbackground="white",highlightthickness=2)
    ],
    [
        tk.Frame(root,bg="purple",width=250,height=250,highlightbackground="white",highlightthickness=2),
        tk.Frame(root,bg="purple",width=250,height=250,highlightbackground="white",highlightthickness=2),
        tk.Frame(root,bg="purple",width=250,height=250,highlightbackground="white",highlightthickness=2)
    ]
]


littleCats=[

    [
        [
            [
                tk.Frame(cat[0][0],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[0][0],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[0][0],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2)
            ],
            [
                tk.Frame(cat[0][0],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[0][0],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[0][0],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2)
            ],
            [
                tk.Frame(cat[0][0],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[0][0],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[0][0],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2)
            ]
        ],
        [
            [
                tk.Frame(cat[0][1],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[0][1],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[0][1],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2)
            ],
            [
                tk.Frame(cat[0][1],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[0][1],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[0][1],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2)
            ],
            [
                tk.Frame(cat[0][1],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[0][1],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[0][1],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2)
            ]
        ],
        [
            [
                tk.Frame(cat[0][2],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[0][2],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[0][2],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2)
            ],
            [
                tk.Frame(cat[0][2],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[0][2],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[0][2],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2)
            ],
            [
                tk.Frame(cat[0][2],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[0][2],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[0][2],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2)
            ]
        ]
    ],
        
    [
        [
            [
                tk.Frame(cat[1][0],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[1][0],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[1][0],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2)
            ],
            [
                tk.Frame(cat[1][0],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[1][0],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[1][0],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2)
            ],
            [
                tk.Frame(cat[1][0],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[1][0],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[1][0],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2)
            ]
        ],
        [
            [
                tk.Frame(cat[1][1],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[1][1],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[1][1],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2)
            ],
            [
                tk.Frame(cat[1][1],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[1][1],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[1][1],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2)
            ],
            [
                tk.Frame(cat[1][1],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[1][1],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[1][1],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2)
            ]
        ],
        [
            [
                tk.Frame(cat[1][2],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[1][2],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[1][2],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2)
            ],
            [
                tk.Frame(cat[1][2],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[1][2],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[1][2],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2)
            ],
            [
                tk.Frame(cat[1][2],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[1][2],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[1][2],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2)
            ]
        ]
    ],

    [
        [
            [
                tk.Frame(cat[2][0],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[2][0],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[2][0],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2)
            ],
            [
                tk.Frame(cat[2][0],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[2][0],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[2][0],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2)
            ],
            [
                tk.Frame(cat[2][0],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[2][0],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[2][0],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2)
            ]
        ],
        [
            [
                tk.Frame(cat[2][1],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[2][1],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[2][1],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2)
            ],
            [
                tk.Frame(cat[2][1],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[2][1],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[2][1],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2)
            ],
            [
                tk.Frame(cat[2][1],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[2][1],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[2][1],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2)
            ]
        ],
        [
            [
                tk.Frame(cat[2][2],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[2][2],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[2][2],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2)
            ],
            [
                tk.Frame(cat[2][2],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[2][2],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[2][2],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2)
            ],
            [
                tk.Frame(cat[2][2],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[2][2],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2),
                tk.Frame(cat[2][2],bg="#B7B7B7",width=75,height=75,highlightbackground="purple",highlightthickness=2)
            ]
        ]
    ]
]

labels=[
    [
        [
            [
                tk.Label(littleCats[0][0][0][0],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[0][0][0][1],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[0][0][0][2],text="",font=("Arial",32),bg="#B7B7B7"),
            ],
            [
                tk.Label(littleCats[0][0][1][0],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[0][0][1][1],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[0][0][1][2],text="",font=("Arial",32),bg="#B7B7B7"),
            ],
            [
                tk.Label(littleCats[0][0][2][0],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[0][0][2][1],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[0][0][2][2],text="",font=("Arial",32),bg="#B7B7B7"), 
            ]
        ],
        [
            [
                tk.Label(littleCats[0][1][0][0],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[0][1][0][1],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[0][1][0][2],text="",font=("Arial",32),bg="#B7B7B7"),
            ],
            [
                tk.Label(littleCats[0][1][1][0],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[0][1][1][1],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[0][1][1][2],text="",font=("Arial",32),bg="#B7B7B7"),
            ],
            [
                tk.Label(littleCats[0][1][2][0],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[0][1][2][1],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[0][1][2][2],text="",font=("Arial",32),bg="#B7B7B7"),
            ]
        ],
        [
            [
                tk.Label(littleCats[0][2][0][0],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[0][2][0][1],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[0][2][0][2],text="",font=("Arial",32),bg="#B7B7B7"),
            ],
            [
                tk.Label(littleCats[0][2][1][0],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[0][2][1][1],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[0][2][1][2],text="",font=("Arial",32),bg="#B7B7B7"),
            ],
            [
                tk.Label(littleCats[0][2][2][0],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[0][2][2][1],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[0][2][2][2],text="",font=("Arial",32),bg="#B7B7B7"),
            ]
        ]
    ],
    [
        [
            [
                tk.Label(littleCats[1][0][0][0],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[1][0][0][1],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[1][0][0][2],text="",font=("Arial",32),bg="#B7B7B7")
            ],
            [
                tk.Label(littleCats[1][0][1][0],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[1][0][1][1],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[1][0][1][2],text="",font=("Arial",32),bg="#B7B7B7")
            ],
            [
                tk.Label(littleCats[1][0][2][0],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[1][0][2][1],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[1][0][2][2],text="",font=("Arial",32),bg="#B7B7B7")
            ]
        ],
        [
            [
                tk.Label(littleCats[1][1][0][0],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[1][1][0][1],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[1][1][0][2],text="",font=("Arial",32),bg="#B7B7B7")
            ],
            [
                tk.Label(littleCats[1][1][1][0],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[1][1][1][1],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[1][1][1][2],text="",font=("Arial",32),bg="#B7B7B7")
            ],
            [
                tk.Label(littleCats[1][1][2][0],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[1][1][2][1],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[1][1][2][2],text="",font=("Arial",32),bg="#B7B7B7")
            ]
        ],
        [
            [
                tk.Label(littleCats[1][2][0][0],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[1][2][0][1],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[1][2][0][2],text="",font=("Arial",32),bg="#B7B7B7")
            ],
            [
                tk.Label(littleCats[1][2][1][0],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[1][2][1][1],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[1][2][1][2],text="",font=("Arial",32),bg="#B7B7B7")
            ],
            [
                tk.Label(littleCats[1][2][2][0],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[1][2][2][1],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[1][2][2][2],text="",font=("Arial",32),bg="#B7B7B7")
            ]
        ]
    ],
    [
        [
            [
                tk.Label(littleCats[2][0][0][0],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[2][0][0][1],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[2][0][0][2],text="",font=("Arial",32),bg="#B7B7B7")
            ],
            [
                tk.Label(littleCats[2][0][1][0],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[2][0][1][1],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[2][0][1][2],text="",font=("Arial",32),bg="#B7B7B7")
            ],
            [
                tk.Label(littleCats[2][0][2][0],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[2][0][2][1],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[2][0][2][2],text="",font=("Arial",32),bg="#B7B7B7")
            ]
        ],
        [
            [
                tk.Label(littleCats[2][1][0][0],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[2][1][0][1],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[2][1][0][2],text="",font=("Arial",32),bg="#B7B7B7")
            ],
            [
                tk.Label(littleCats[2][1][1][0],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[2][1][1][1],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[2][1][1][2],text="",font=("Arial",32),bg="#B7B7B7")
            ],
            [
                tk.Label(littleCats[2][1][2][0],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[2][1][2][1],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[2][1][2][2],text="",font=("Arial",32),bg="#B7B7B7")
            ]
        ],
        [
            [
                tk.Label(littleCats[2][2][0][0],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[2][2][0][1],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[2][2][0][2],text="",font=("Arial",32),bg="#B7B7B7")
            ],
            [
                tk.Label(littleCats[2][2][1][0],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[2][2][1][1],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[2][2][1][2],text="",font=("Arial",32),bg="#B7B7B7")
            ],
            [
                tk.Label(littleCats[2][2][2][0],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[2][2][2][1],text="",font=("Arial",32),bg="#B7B7B7"),
                tk.Label(littleCats[2][2][2][2],text="",font=("Arial",32),bg="#B7B7B7")
            ]
        ]
    ]
]

def principalEvent(event,rowOne,columnOne,row,column):
    event.config(bg="red")
    #agregar condición para que coloque X u O cada vez que este evento sea accionado 
    labels[rowOne][columnOne][row][column].config(text="O",bg="red")


for row in range(3):
    for column in range(3):
        cat[row][column].grid(row=row,column=column)

for rowOne in range(3):
    for columnOne in range(3):
        for row in range(3):
            for column in range(3):
                littleCats[rowOne][columnOne][row][column].grid(row=row,column=column)
                littleCats[rowOne][columnOne][row][column].bind("<Button-1>",lambda event,eve=littleCats[rowOne][columnOne][row][column],one=rowOne,two=columnOne,three=row,four=column:principalEvent(eve,one,two,three,four))
                labels[rowOne][columnOne][row][column].place(x=19,y=10)


root.mainloop()
